<?php

return [

    // pizze
    [
        "name" => "Pizza bianca",
        "description" => "pizza senza nulla a chi piace solo la pasta ma non il condimento",
        "price" => 2.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Pizza margerita",
        "description" => "una classica pizza margerita",
        "price" => 3.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "pizza con ananas",
        "description" => "sei un masochista, questa e' la pizza giusta per te",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "pizza diavola",
        "description" => "la pizza per chi vuole avere l'inferno in bocca mentre la mangia",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "pizza 4 formaggi",
        "description" => "la pizza quando solo la mozzarella non ti basta",
        "price" => 7.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "pizza 4 stagioni",
        "description" => "la pizza quando hai voglia di 4 pizze insieme",
        "price" => 7.99,
        "available" => "true",
        "image" => "",
    ],

    //paste
    [
        "name" => "pasta in bianco",
        "description" => "la pasta senza nulla, si spera che ci mettano almeno il sale",
        "price" => 4.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "pasta al pomodoro",
        "description" => "classica pasta al pomodoro, perche ti aspettavi altro?",
        "price" => 4.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "pasta al ragu",
        "description" => "una pastaal pomodoro ma con l'aggiunta di carne",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "pasta al pesto",
        "description" => "se mangi questa pasta dopo ti metterai a dire belin come un vero genovese",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "pasta con le vongole",
        "description" => "la pasta per chi non si accontenta di mangiare ma vuole anche la sfida di aprire quelle cazzo di vongole",
        "price" => 10.99,
        "available" => "true",
        "image" => "",
    ],
    //tacos
    [
        "name" => "Tacos classico",
        "description" => "Tacos classico, con semplicemente tutti gli ingredienti, non e' cosi un tacos classico??",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Tacos piccante",
        "description" => "Tacos classico ma con molto piu piccante",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Tacos vegetariano",
        "description" => "Tacos classico ma sena carne, tranquilli pero, il picvcante c'e' comunque",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    //burrito
    [
        "name" => "Burrito classico",
        "description" => "Burrito classico, con semplicemente tutti gli ingredienti, non e' cosi un burrito classico??",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Burrito piccante",
        "description" => "Burrito classico ma con molto piu piccante",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Burrito vegetariano",
        "description" => "Burrito classico ma sena carne, tranquilli pero, il picvcante c'e' comunque",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    //cinese
    [
        "name" => "Riso alla cantonese",
        "description" => "Riso tipico cinese con prosciutto cotto",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "anatra all'arancia",
        "description" => "anatra all'arancia, non chiedetemi il perche dell'arancia",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "involtini di gamberi",
        "description" => "semplici involtini di gamberi",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "tofu con carne piccante",
        "description" => "tofu con carne piccante",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    //amerticano
    // [
    //     "name" => "Hamburger generico",
    //     "description" => "hamburger generico con 2000kcal",
    //     "price" => 5.99,
    //     "available" => "true",
    //     "image" => "",
    // ],
    // [
    //     "name" => "Hamburger kid",
    //     "description" => "hamburger generico ma con solo 1000kcal",
    //     "price" => 5.99,
    //     "available" => "true",
    //     "image" => "",
    // ],
    // [
    //     "name" => "Hamburger hard",
    //     "description" => "hamburger generico ma con solo 10000kcal con l'aggiunta di 2kg di patatine compreso nel prezzo",
    //     "price" => 40.99,
    //     "available" => "true",
    //     "image" => "",
    // ],
    [
        "name" => "Burger classico",
        "description" => "Hamburger 180gr, insalata, pomodoro, ketchup servito con patate dorate",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Chicken burger",
        "description" => "120gr di pollo croccante ai cereali, maionese, pomodoro, insalata servito con patate dorate",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "fish burger",
        "description" => "120gr di merluzzo in pastella, insalata, pomodoro, guacamole, servito con patate dorate",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Patatine fritte",
        "description" => "120gr di merluzzo in pastella, insalata, pomodoro, guacamole, servito con patate dorate",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    //indiani
    [
        "name" => "Dal sup vegetariano",
        "description" => "Zuppa di lenticchie con verdure",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Basmati bianco",
        "description" => "Riso bianco cotto al vapore",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Chicken curry",
        "description" => "Pollo curry classico con spezie",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Chicken dhansak",
        "description" => "Pollo cotto nella crema di lenticchie",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Panir tikka",
        "description" => "Formaggio magro marinato e cotto nel forno tandoori",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Palak paneer",
        "description" => "Crema di spinaci con la ricotta magra da accompagnare al pane indiano",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    //gappionese
    // [
    //     "name" => "Ramen",
    //     "description" => "se hai visto almeno una volta naruto sai di cosa stiamo parlando",
    //     "price" => 5.99,
    //     "available" => "true",
    //     "image" => "",
    // ],
    [
        "name" => "Ramen",
        "description" => "Brodo con spagetti e carne",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "1. Involtino di gamberi",
        "description" => "Harumaki, 4pezzi",
        "price" => 4.00,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Ebi shumai 5pz",
        "description" => "Ravioli di gamberi al vapore",
        "price" => 5.00,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Maguro",
        "description" => "Tonno, 2 pezzi",
        "price" => 3.00,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Gunkan spicy salmone e alga",
        "description" => "2 pezzi",
        "price" => 5.00,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Salmone a pezzi",
        "description" => "Salmone pezzi, avocado",
        "price" => 8.00,
        "available" => "true",
        "image" => "",
    ],
    //gelateria
    [
        "name" => "Yogurt bianco - normale",
        "description" => "Yogurt fresco intero, senza zucchero",
        "price" => 3.50,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Frutta rossa",
        "description" => "Frutta sempre fresca - fragole, mirtilli, lamponi",
        "price" => 3.50,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Crepe al dulce de leche",
        "description" => "",
        "price" => 4.00,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Tramezzino Tonno",
        "description" => "Con pomodoro, insalata e maionese",
        "price" => 3.50,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Piadina caprese",
        "description" => "Mozzarella fresca, pomodoro e origano",
        "price" => 5.00,
        "available" => "true",
        "image" => "",
    ],
    //kebab
    [
        "name" => "Piatto kebab solo carne",
        "description" => "",
        "price" => 8.50,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Sfilatino kebab",
        "description" => "Pomodoro, mozzarella, carne, cipolla, salsa yogurt e piccante",
        "price" => 8.00,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Focaccia kebab completa",
        "description" => "",
        "price" => 8.00,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Piadina kebab",
        "description" => "Carne di vitello e tacchino, insalata, pomodoro, cipolle, salsa yogurt e salsa piccante",
        "price" => 4.50,
        "available" => "true",
        "image" => "",
    ],
    //vegetariano
    [
        "name" => "Haruka Sushi",
        "description" => "suchi vegetariano",
        "price" => 10.00,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Ramen vegetariano",
        "description" => "Ramen vegetariano con shishito, mizuna, enoki-take e tofu",
        "price" => 15.00,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "pizza vegetariana",
        "description" => "",
        "price" => 10.00,
        "available" => "true",
        "image" => "",
    ],
    //fast food
    [
        "name" => "Burger classico",
        "description" => "Hamburger 180gr, insalata, pomodoro, ketchup servito con patate dorate",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Chicken burger",
        "description" => "120gr di pollo croccante ai cereali, maionese, pomodoro, insalata servito con patate dorate",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "fish burger",
        "description" => "120gr di merluzzo in pastella, insalata, pomodoro, guacamole, servito con patate dorate",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Patatine fritte",
        "description" => "120gr di merluzzo in pastella, insalata, pomodoro, guacamole, servito con patate dorate",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "pasta al pomodoro",
        "description" => "classica pasta al pomodoro, perche ti aspettavi altro?",
        "price" => 4.99,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "pasta al ragu",
        "description" => "una pasta al pomodoro ma con l'aggiunta di carne",
        "price" => 5.99,
        "available" => "true",
        "image" => "",
    ],
    //dessert
    [
        "name" => "Vaschetta 350gr",
        "description" => "Fino a tre gusti. Puoi scegliere sia sorbetti - preparati con frutta fresca - che creme - preparati sempre con materie prime di ottima qualità, latte fresco, panna fresca",
        "price" => 7.50,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Yogurt con frutta verde - grande",
        "description" => "Yogurt fresco intero, senza zucchero - banane, mele, pere, pesche, albicocche",
        "price" => 5.00,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Frutta verde",
        "description" => "Frutta sempre fresca - banane, mele, pere, pesche, albicocche",
        "price" => 3.50,
        "available" => "true",
        "image" => "",
    ],
    //poke
    [
        "name" => "Poke Sunny Salmon",
        "description" => "Riso bianco, Juicy Salmon, Avocado, Edamame, Cavolo rosso, Salsa speciale,Crema di avocado, Crispy Mix Alghe e Wasabi, Sesamo",
        "price" => 9.95,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Poke Spring Break",
        "description" => "Riso Integrale, Gamberi, Avocado, Zucchine, Barbabietola, Cavolo Rosso, Germogli di Porro, Salsa Spring, Olio Sale e Limone, Sesamo",
        "price" => 12.95,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Poke Avocado Toast",
        "description" => "Pane Tostato, Avocado, Feta, Olio Sale e Limone, Peperoncino",
        "price" => 6.00,
        "available" => "true",
        "image" => "",
    ],
    [
        "name" => "Poke White Fish",
        "description" => "Riso bianco, branzino, avocado, mango, zenzero fresco, cipollotto, salsa Hawaii, sesamo",
        "price" => 11.95,
        "available" => "true",
        "image" => "",
    ],

];
