<?php

return [

    // PIZZA

    [
        "name" => "Marinara",
        "description" => "Pomodoro, Basilico",
        "price" => 4,
        "available" => true,
        "image" => "",
        "restaurant_id" => 1,
    ],
    [
        "name" => "Margherita",
        "description" => "Pomodoro, Mozzarella, Basilico",
        "price" => 5,
        "available" => true,
        "image" => "",
        "restaurant_id" => 2,
    ],
    [
        "name" => "ZuccaBacon",
        "description" => "Pomodoro, Mozzarella, Fiore di Zucca e Bacon",
        "price" => 8,
        "available" => true,
        "image" => "",
        "restaurant_id" => 1,
    ],
    [
        "name" => "Diavola",
        "description" => "Pomodoro, Mozzarella, Salamino piccante",
        "price" => 6,
        "available" => true,
        "image" => "",
        "restaurant_id" => 1,
    ],
    [
        "name" => "Pizza Prosciutto e Funghi",
        "description" => "Pomodoro, Mozzarella, Prosciutto cotto, Funghi",
        "price" => 7.50,
        "available" => true,
        "image" => "",
        "restaurant_id" => 2,
    ],
    [
        "name" => "Calzone Classico",
        "description" => "Pomodoro, Mozzarella, Prosciutto cotto",
        "price" => 8,
        "available" => true,
        "image" => "",
        "restaurant_id" => 2,
    ],

    // ITALIANO

    [
        "name" => "Spaghetti alle vongole",
        "description" => "",
        "price" => 17,
        "available" => true,
        "image" => "",
        "restaurant_id" => 3,
    ],
    [
        "name" => "Pasta al pomodoro",
        "description" => "",
        "price" => 12,
        "available" => true,
        "image" => "",
        "restaurant_id" => 3,
    ],
    [
        "name" => "Risotto alla pescatora",
        "description" => "Risotto, Gamberi, Cozze, Vongole, Polpo, Seppia, Calamari",
        "price" => 19,
        "available" => true,
        "image" => "",
        "restaurant_id" => 3,
    ],
    [
        "name" => "Fettuccine alla bolognese",
        "description" => "Fettuccine con ragu' e macinato",
        "price" => 9,
        "available" => true,
        "image" => "",
        "restaurant_id" => 3,
    ],
    [
        "name" => "Gnocchi alla sorrentina",
        "description" => "Gnocchi, Pomodoro, Provola e Basilico",
        "price" => 9,
        "available" => true,
        "image" => "",
        "restaurant_id" => 3,
    ],

    // MESSICANO

    [
        "name" => "Tacos Manzo",
        "description" => "Tre tortillas ripiene di manzo servite con pico de gallo, guacamole e lime",
        "price" => 14,
        "available" => true,
        "image" => "",
        "restaurant_id" => 10,
    ],
    [
        "name" => "Tacos Pollo",
        "description" => "Tre tortillas ripiene di pollo servite con pico de gallo, guacamole e lime",
        "price" => 12,
        "available" => true,
        "image" => "",
        "restaurant_id" => 11,
    ],
    [
        "name" => "Chili con carne",
        "description" => "Cubetti di carne di manzo e maiale cucinati con fagioli messicani, pomodori, cipolla, peperoni",
        "price" => 13,
        "available" => true,
        "image" => "",
        "restaurant_id" => 10,
    ],
    [
        "name" => "Burrito Pollo",
        "description" => "Tortillas di farina ripiena con pollo, formaggio, peperoni e cipolla",
        "price" => 15,
        "available" => true,
        "image" => "",
        "restaurant_id" => 11,
    ],
    [
        "name" => "Burrito Manzo",
        "description" => "Tortillas di farina ripiena con manzo e formaggio, riso mex e fagioli neri",
        "price" => 15,
        "available" => true,
        "image" => "",
        "restaurant_id" => 10,
    ],
    [
        "name" => "Tortillas di grano",
        "description" => "4 tortillas di grano",
        "price" => 3,
        "available" => true,
        "image" => "",
        "restaurant_id" => 11,
    ],

    // CINESE

    [
        "name" => "Riso Cantonese",
        "description" => "Riso, uova, verdure, pollo",
        "price" => 7,
        "available" => true,
        "image" => "",
        "restaurant_id" => 4,
    ],
    [
        "name" => "Anatra all'arancia",
        "description" => "",
        "price" => 8,
        "available" => true,
        "image" => "",
        "restaurant_id" => 5,
    ],
    [
        "name" => "Udon con verdure",
        "description" => "",
        "price" => 7,
        "available" => true,
        "image" => "",
        "restaurant_id" => 6,
    ],
    [
        "name" => "Shiratake di verdure e gamberi",
        "description" => "",
        "price" => 9,
        "available" => true,
        "image" => "",
        "restaurant_id" => 7,
    ],

    // AMERICANO

    [
        "name" => "Hamburger",
        "description" => "",
        "price" => 13,
        "available" => true,
        "image" => "",
        "restaurant_id" => 18,
    ],
    [
        "name" => "Cheeseburger",
        "description" => "",
        "price" => 13,
        "available" => true,
        "image" => "",
        "restaurant_id" => 19,
    ],
    [
        "name" => "Cheesburger Bacon",
        "description" => "",
        "price" => 14,
        "available" => true,
        "image" => "",
        "restaurant_id" => 20,
    ],
    [
        "name" => "Baconburger",
        "description" => "",
        "price" => 15,
        "available" => true,
        "image" => "",
        "restaurant_id" => 21,
    ],
    [
        "name" => "Chicken burger",
        "description" => "",
        "price" => 12,
        "available" => true,
        "image" => "",
        "restaurant_id" => 18,
    ],
    [
        "name" => "Patatine fritte",
        "description" => "",
        "price" => 5,
        "available" => true,
        "image" => "",
        "restaurant_id" => 19,
    ],

    // INDIANO

    [
        "name" => "Dal sup vegetariano",
        "description" => "Zuppa di lenticchie con verdure",
        "price" => 8.50,
        "available" => true,
        "image" => "",
        "restaurant_id" => 25,
    ],
    [
        "name" => "Basmati bianco",
        "description" => "Riso bianco cotto al vapore",
        "price" => 5,
        "available" => true,
        "image" => "",
        "restaurant_id" => 26,
    ],
    [
        "name" => "Chicken curry",
        "description" => "Pollo curry classico con spezie e verdure",
        "price" => 9,
        "available" => true,
        "image" => "",
        "restaurant_id" => 25,
    ],
    [
        "name" => "Chicken dhansak",
        "description" => "Pollo cotto nella crema di lenticchie",
        "price" => 12,
        "available" => true,
        "image" => "",
        "restaurant_id" => 26,
    ],
    [
        "name" => "Panir tikka",
        "description" => "Formaggio magro marinato e cotto nel forno tandoori",
        "price" => 7.5,
        "available" => true,
        "image" => "",
        "restaurant_id" => 25,
    ],
    [
        "name" => "Palak paneer",
        "description" => "Crema di spinaci con la ricotta magra da accompagnare al pane indiano",
        "price" => 8,
        "available" => true,
        "image" => "",
        "restaurant_id" => 26,
    ],

    // GIAPPONESE

    [
        "name" => "Ramen di maiale",
        "description" => "",
        "price" => 15,
        "available" => true,
        "image" => "",
        "restaurant_id" => 4,
    ],
    [
        "name" => "Harumaki",
        "description" => "4 pezzi",
        "price" => 4.00,
        "available" => true,
        "image" => "",
        "restaurant_id" => 5,
    ],
    [
        "name" => "Ebi shumai 5pz",
        "description" => "",
        "price" => 5.00,
        "available" => true,
        "image" => "",
        "restaurant_id" => 6,
    ],
    [
        "name" => "Tonno 2 pezzi",
        "description" => "",
        "price" => 3.00,
        "available" => true,
        "image" => "",
        "restaurant_id" => 7,
    ],
    [
        "name" => "Gunkan spicy salmone e alga",
        "description" => "",
        "price" => 5.00,
        "available" => true,
        "image" => "",
        "restaurant_id" => 4,
    ],
    [
        "name" => "Salmone a pezzi",
        "description" => "Salmone pezzi, avocado",
        "price" => 8.00,
        "available" => true,
        "image" => "",
        "restaurant_id" => 5,
    ],

    // GELATERIA

    [
        "name" => "Yogurt bianco",
        "description" => "Yogurt fresco intero, senza zucchero",
        "price" => 3.50,
        "available" => true,
        "image" => "",
        "restaurant_id" => 12,
    ],
    [
        "name" => "Frutta rossa",
        "description" => "fragole, mirtilli, lamponi",
        "price" => 4,
        "available" => true,
        "image" => "",
        "restaurant_id" => 13,
    ],
    [
        "name" => "Crepes al dulce de leche",
        "description" => "",
        "price" => 4.00,
        "available" => true,
        "image" => "",
        "restaurant_id" => 14,
    ],
    [
        "name" => "Crepes alla Nutella",
        "description" => "",
        "price" => 4.50,
        "available" => true,
        "image" => "",
        "restaurant_id" => 14,
    ],

    // KEBAB

    [
        "name" => "Piatto kebab",
        "description" => "",
        "price" => 6.50,
        "available" => true,
        "image" => "",
        "restaurant_id" => 8,
    ],
    [
        "name" => "Sfilatino kebab",
        "description" => "Pomodoro, mozzarella, carne, cipolla, salsa yogurt e piccante",
        "price" => 8.00,
        "available" => true,
        "image" => "",
        "restaurant_id" => 9,
    ],
    [
        "name" => "Focaccia kebab completa",
        "description" => "",
        "price" => 8.00,
        "available" => true,
        "image" => "",
        "restaurant_id" => 8,
    ],
    [
        "name" => "Piadina kebab",
        "description" => "Carne di vitello e tacchino, insalata, pomodoro, cipolle, salsa yogurt e salsa piccante",
        "price" => 5.50,
        "available" => true,
        "image" => "",
        "restaurant_id" => 9,
    ],

    // VEGETARIANO

    [
        "name" => "Haruka Sushi",
        "description" => "Sushi vegetariano",
        "price" => 10.00,
        "available" => true,
        "image" => "",
        "restaurant_id" => 22,
    ],
    [
        "name" => "Ramen vegetariano",
        "description" => "Ramen vegetariano con shishito, mizuna, enoki-take e tofu",
        "price" => 15.00,
        "available" => true,
        "image" => "",
        "restaurant_id" => 23,
    ],
    [
        "name" => "Pizza vegetariana",
        "description" => "",
        "price" => 8.00,
        "available" => true,
        "image" => "",
        "restaurant_id" => 24,
    ],

    // FAST-FOOD

    [
        "name" => "Hamburger",
        "description" => "Hamburger 180gr, insalata, pomodoro, ketchup servito con patate dorate",
        "price" => 5.99,
        "available" => true,
        "image" => "",
        "restaurant_id" => 19,
    ],
    [
        "name" => "Chickenburger",
        "description" => "120gr di pollo croccante ai cereali, maionese, pomodoro, insalata servito con patate dorate",
        "price" => 6.99,
        "available" => true,
        "image" => "",
        "restaurant_id" => 20,
    ],
    [
        "name" => "Fishburger",
        "description" => "120gr di merluzzo in pastella, insalata, pomodoro, guacamole, servito con patate dorate",
        "price" => 4.99,
        "available" => true,
        "image" => "",
        "restaurant_id" => 21,
    ],
    [
        "name" => "Patatine fritte",
        "description" => "",
        "price" => 2.99,
        "available" => true,
        "image" => "",
        "restaurant_id" => 18,
    ],

    // POKE

    [
        "name" => "Poke Sunny Salmon",
        "description" => "Riso bianco, Juicy Salmon, Avocado, Edamame, Cavolo rosso, Salsa speciale,Crema di avocado, Crispy Mix Alghe e Wasabi, Sesamo",
        "price" => 9.95,
        "available" => true,
        "image" => "",
        "restaurant_id" => 15,
    ],
    [
        "name" => "Poke Spring Break",
        "description" => "Riso Integrale, Gamberi, Avocado, Zucchine, Barbabietola, Cavolo Rosso, Germogli di Porro, Salsa Spring, Olio Sale e Limone, Sesamo",
        "price" => 12.95,
        "available" => true,
        "image" => "",
        "restaurant_id" => 16,
    ],
    [
        "name" => "Poke Avocado Toast",
        "description" => "Pane Tostato, Avocado, Feta, Olio Sale e Limone, Peperoncino",
        "price" => 6.00,
        "available" => true,
        "image" => "",
        "restaurant_id" => 17,
    ],
    [
        "name" => "Poke White Fish",
        "description" => "Riso bianco, branzino, avocado, mango, zenzero fresco, cipollotto, salsa Hawaii, sesamo",
        "price" => 11.95,
        "available" => true,
        "image" => "",
        "restaurant_id" => 15,
    ],

];
